// <auto-generated />
using System;
using Hashing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hashing.Migrations
{
    [DbContext(typeof(HashingContext))]
    partial class HashingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Hashing.HashInfo", b =>
                {
                    b.Property<int>("HashId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Algorithm")
                        .IsRequired();

                    b.Property<byte[]>("Hash")
                        .IsRequired();

                    b.Property<DateTime>("MTime");

                    b.Property<byte[]>("PathHash")
                        .IsRequired();

                    b.Property<uint>("Size");

                    b.HasKey("HashId");

                    b.ToTable("HashInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
